<?php

// autoload.php @generated by Composer

require_once 'core/Psr4AutoloaderClass.php';
$loader = new Psr4AutoloaderClass();
$loader->register();

$loader->addNamespace('core', __DIR__ . '/core');
$loader->addNamespace('app', __DIR__ . '/app');